services:
  tasks-ms:
    image: "ghcr.io/essamsung/tasks-ms:1.1.0"
    container_name: tasks-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - tasksnet
    deploy:
      resources:
        limits:
          memory: 900m

networks:
  tasksnet:
    driver: "bridge"
